[project]
name = "aula06-bootcamp"
version = "0.1.0"
description = ""
authors = [
    {name = "ericfloriano",email = "ericfloriano@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flake8 (>=7.2.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
